### ISSUE TITLE
install broken since lz4 updated to 6.0.4

### ISSUE THREAD

**Issue by leoparis89** [indix/kafkajs-lz4#4]
OSX 10.13.6
node v12.18.2
yarn v1.22.4

Can't install kafkajs-lz4 since it now pulls lz4 6.0.4 which is broken.

I get this error after `yarn add kafkajs-lz4`

> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CXX(target) Release/obj.target/lz4/lib/binding/lz4_binding.o
> ../lib/binding/lz4_binding.cc:8:10: fatal error: '../../deps/lz4/lib/lz4.h' file not found
> #include "../../deps/lz4/lib/lz4.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [Release/obj.target/lz4/lib/binding/lz4_binding.o] Error 1
> gyp ERR! build error

**Comment by keyvhinng** [comment]
+1

**Comment by lalit117** [comment]
+1

**Comment by herrkessler** [comment]
+1

**Comment by chakshu222** [comment]
+1

**Comment by NikhilManapure** [comment]
+1

**Comment by paambaati** [comment]
Quick Github etiquette primer for the folks commenting with a `+1` — please refrain from doing so. It just sends out notification emails to all subscribers without providing any useful information. If you'd like to get updates, please click on the 'Subscribe' button to get notified of future updates.

In the meantime, please follow https://github.com/pierrec/node-lz4/issues/97 as that is the original upstream issue. Once that gets fixed, this package will work again.

Closing this and making https://github.com/indix/kafkajs-lz4/issues/3 the canonical issue for this problem.
